// ============================================================
//  games-data.js  —  Anagrafica completa dei giochi
//  Importare questo file PRIMA di script.js nell'HTML:
//    <script src="games-data.js"></script>
//    <script src="script.js"></script>
// ============================================================

const gamesRaw = [
  {
    id: 'game-1',
    name: 'Cascadia',
    description: `Cascadia è un gioco da tavolo per 1-4 giocatori della durata di circa 30-45 minuti, in cui i partecipanti costruiscono ecosistemi combinando tessere habitat e gettoni fauna per ottenere punti vittoria, bilanciando strategia e semplicità.`,
    image: 'games/Cascadia.jpg',
    players: { min: 1, max: 4 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['strategico', 'familiare', 'piazzamento tessere', 'medio', 'solitario'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 1.85,
    pdfLink: 'https://www.alderac.com/wp-content/uploads/2021/08/Cascadia-Rules.pdf'
  },
  {
    id: 'game-2',
    name: 'Blood Rage',
    description: `Blood Rage è un gioco da tavolo per 2-4 giocatori della durata di circa 60-90 minuti, in cui i partecipanti guidano clan vichinghi in battaglie epiche, saccheggiando terre, guadagnando gloria e avanzando sul Ragnarök, combinando strategia di combattimento, gestione carte e controllo del territorio.`,
    image: 'games/Blood Rage.jpg',
    players: { min: 2, max: 4 },
    time: { min: 60, max: 120 },
    playtimeCategory: '> 60 min',
    tags: ['strategico', 'controllo territorio', 'competitivo', 'pesante'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: 2.88,
    pdfLink: 'https://www.the-forge.it/wp-content/uploads/2019/11/BloodRage_Rulebook_ITA.pdf'
  },
  {
    id: 'game-3',
    name: 'Forest Shuffle',
    description: `Forest Shuffle è un gioco di carte strategico per 2-5 giocatori della durata di circa 40-60 minuti, in cui i partecipanti competono per raccogliere gli alberi più preziosi e attirare specie diverse per creare un habitat forestale equilibrato e ottenere il maggior numero di punti vittoria.`,
    image: 'games/Forest Shuffle.jpg',
    players: { min: 2, max: 5 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['carte', 'strategico', 'medio', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: '2 (non da BGG)',
    pdfLink: 'https://www.brdgmz.nl/wp-content/uploads/Appendix-Forest-Shuffle-English.pdf'
  },
  {
    id: 'game-4',
    name: 'Carcassonne',
    description: `Carcassonne è un gioco da tavolo per 2-5 giocatori della durata di circa 30-45 minuti, in cui i partecipanti piazzano tessere per costruire città, strade e campi, collocando i propri meeple strategicamente per guadagnare punti vittoria e dominare il paesaggio medievale.`,
    image: 'games/Carcassonne.jpg',
    players: { min: 2, max: 5 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['familiare', 'piazzamento tessere', 'leggero', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 1.91,
    pdfLink: 'https://parpignol.info/wp-content/uploads/2017/09/Carcassonne.pdf'
  },
  {
    id: 'game-5',
    name: 'Puerto Rico',
    description: `Puerto Rico è un gioco da tavolo per 2-5 giocatori della durata di circa 90-150 minuti, in cui i partecipanti gestiscono piantagioni, edifici e coloni sull'isola di Puerto Rico, ottimizzando produzione e spedizioni per guadagnare punti vittoria e diventare il governatore più potente.`,
    image: 'games/Puerto Rico.jpg',
    players: { min: 2, max: 5 },
    time: { min: 60, max: 120 },
    playtimeCategory: '> 60 min',
    tags: ['strategico', 'gestionale', 'pesante', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: 3.27,
    pdfLink: 'https://www.riograndegames.com/wp-content/uploads/2019/08/Puerto-Rico-Deluxe-Rules.pdf'
  },
  {
    id: 'game-6',
    name: 'The Castles of Burgundy',
    description: `The Castles of Burgundy è un gioco da tavolo per 2-4 giocatori della durata di circa 30-90 minuti, in cui i partecipanti sviluppano la propria regione nel Ducato di Borgogna piazzando tessere, commerciando e sfruttando abilità speciali per guadagnare punti vittoria strategicamente.`,
    image: 'games/The Castles of Burgundy.jpg',
    players: { min: 2, max: 4 },
    time: { min: 60, max: 120 },
    playtimeCategory: '> 60 min',
    tags: ['strategico', 'gestionale', 'medio', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: 2.99,
    pdfLink: 'https://cdn.1j1ju.com/medias/04/f5/f9-the-castles-of-burgundy-rulebook.pdf'
  },
  {
    id: 'game-7',
    name: 'HEAT',
    description: `HEAT è un gioco da tavolo di corse automobilistiche per 1-6 giocatori della durata di circa 30-60 minuti, in cui i partecipanti gestiscono velocità, curve e stress del motore per tagliare il traguardo per primi, combinando gestione della mano e tattica.`,
    image: 'games/heat.jpg',
    players: { min: 1, max: 6 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['corse', 'familiare', 'competitivo', 'medio', 'solitario'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 2.4,
    pdfLink: 'https://it.scribd.com/document/737796843/Heat-Regolamento-ITA'
  },
  {
    id: 'game-8',
    name: '7 Wonders',
    description: `7 Wonders è un gioco di carte per 2-7 giocatori della durata di circa 30 minuti, in cui i partecipanti sviluppano una civiltà attraverso tre ere costruendo edifici, potenziando l'economia, la scienza e l'esercito per ottenere il maggior numero di punti vittoria.`,
    image: 'games/7 wonders_.jpg',
    players: { min: 2, max: 7 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['carte', 'strategico', 'gruppi numerosi', 'medio'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 2.32,
    pdfLink: 'https://www.migliorigiochi.eu/wp-content/uploads/2017/12/7-wonders-regole.pdf'
  },
  {
    id: 'game-9',
    name: 'Ticket to Ride',
    description: `Ticket to Ride è un gioco da tavolo per 2-5 giocatori della durata di circa 30-60 minuti, in cui i partecipanti costruiscono linee ferroviarie collegando città su una mappa, completando obiettivi segreti e ottimizzando percorsi per fare punti.`,
    image: 'games/ticket to ride.jpg',
    players: { min: 2, max: 5 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['familiare', 'strategico', 'medio', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 1.88,
    pdfLink: 'https://www.goblins.net/files/downloads/tickettorideeurope_ITA.pdf'
  },
  {
    id: 'game-10',
    name: 'Wingspan',
    description: `Wingspan è un gioco da tavolo strategico per 1-5 giocatori della durata di circa 40-70 minuti, in cui i partecipanti attirano uccelli nei propri habitat, creando sinergie tra carte per ottenere risorse, uova e punti vittoria.`,
    image: 'games/Wingspan.jpg',
    imageClass: 'img-horizontal',
    players: { min: 1, max: 5 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['strategico', 'gestionale', 'medio', 'solitario'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: 2.46,
    pdfLink: 'https://it.scribd.com/doc/190219285/Wingspan-Italiano'
  },
  {
    id: 'game-11',
    name: 'Skull King',
    description: `Skull King è un gioco di carte di prese per 2-6 giocatori della durata di circa 30-45 minuti, in cui i partecipanti fanno previsioni sul numero di prese che riusciranno a vincere, utilizzando carte speciali e bluff per ottenere punti.`,
    image: 'games/skull king old.jpg',
    players: { min: 2, max: 6 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'carte', 'bluff', 'gruppi numerosi', 'leggero'],
    macroCategory: 'party game',
    difficulty: 0,
    weightBGG: '0 (non da BGG)',
    pdfLink: 'https://www.schmidtspiele.de/files/Produkte/7/75024%20-%20Skull%20King/75024_Skull_King_DE_FR_IT.pdf'
  },
  {
    id: 'game-12',
    name: 'Samurai Sword',
    description: `Samurai Sword è un gioco di carte per 3-7 giocatori della durata di circa 30 minuti, ambientato nel Giappone feudale, in cui i partecipanti assumono ruoli segreti e si sfidano usando carte azione per eliminare gli avversari e raggiungere i propri obiettivi.`,
    image: 'games/samurai1.jpg',
    players: { min: 3, max: 7 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'ruoli segreti', 'carte', 'leggero'],
    macroCategory: 'party game',
    difficulty: 2,
    weightBGG: '1.76',
    pdfLink: 'https://www.goblins.net/files/downloads/samurai_sword-regole.pdf'
  },
  {
    id: 'game-13',
    name: 'Le rovine di Arnak',
    description: `Le rovine di Arnak è un gioco da tavolo per 1-4 giocatori della durata di circa 60-120 minuti, in cui i partecipanti esplorano un'isola misteriosa combinando deck-building e piazzamento lavoratori per scoprire rovine, combattere guardiani e ottenere punti.`,
    image: 'games/arnak.jpg',
    players: { min: 1, max: 4 },
    time: { min: 60, max: 120 },
    playtimeCategory: '> 60 min',
    tags: ['strategico', 'deck-building', 'piazzamento lavoratori', 'pesante', 'solitario'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: 2.9,
     pdfLink:'https://www.brickone.it/wp-content/uploads/2022/02/Istruzioni-di-gioco-rovine-perdute-di-arnak.pdf?srsltid=AfmBOopChYAhOJFPmYViMr1e2ql-QBq0bFcHVnhIK7elMOTlNn-3vlAE'
  },
  {
    id: 'game-14',
    name: 'Dorfromantik: The Board Game',
    description: `Dorfromantik: The Board Game è un gioco cooperativo per 1-6 giocatori della durata di circa 30-60 minuti, in cui i partecipanti costruiscono un paesaggio armonioso piazzando tessere per completare obiettivi e sbloccare nuovi contenuti.`,
    image: 'games/Dorfromantik.jpg',
    players: { min: 1, max: 6 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['cooperativo', 'familiare', 'piazzamento tessere', 'rilassante'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 1.75,
    pdfLink:'https://www.bigcream.it/upload/riviste/articolo/file_28351.pdf'
  },
  {
    id: 'game-15',
    name: 'sgablab',
    description: `Sgablab è un gioco di carte per 2-6 giocatori della durata di circa 20-30 minuti, in cui i partecipanti cercano di catturare creature leggendarie utilizzando strategia, fortuna e colpi di scena per accumulare punti.`,
    image: 'games/sgablab.png',
    imageClass: 'img-soft-cover',
    players: { min: 2, max: 6 },
    time: { min: 10, max: 30 },
    playtimeCategory: '< 30 min',
    tags: ['carte', 'leggero', 'familiare', 'competitivo'],
    macroCategory: 'party game',
    difficulty: 2,
    weightBGG: '1.8',
    pdfLink: '/games/Regolamento_sgablab.pdf'
  },
 {
    id: 'game-16',
    name: 'Scotland Yard',
    description: `Scotland Yard è un gioco da tavolo di deduzione per 3-6 giocatori della durata di circa 45-60 minuti, in cui un giocatore interpreta Mister X mentre gli altri sono detective che collaborano per rintracciarlo muovendosi su una mappa di Londra usando indizi e logica.`,
    image: 'games/scotland yard.jpg',
    imageClass: 'img-soft-cover',
    players: { min: 3, max: 6 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['deduzione', 'movimento nascosto', 'gruppo', 'medio'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 2.08,
    pdfLink: 'https://www.manualeduso.it/manuals/243247/ravensburger-scotland-yard.html'
  },
  {
    id: 'game-17',
    name: 'Exploding Kittens',
    description: `Exploding Kittens è un gioco di carte per 2-5 giocatori della durata di circa 15-20 minuti, in cui i partecipanti pescano carte evitando di esplodere, usando azioni folli, bluff e colpi bassi per rimanere gli ultimi in gioco.`,
    image: 'games/exploding kittens.jpg',
    imageClass: 'img-horizontal',
    players: { min: 2, max: 5 },
    time: { min: 10, max: 30 },
    playtimeCategory: '< 30 min',
    tags: ['party', 'carte', 'bluff', 'leggero', 'familiare'],
    macroCategory: 'party game',
    difficulty: 0,
    weightBGG: 1.07,
    pdfLink: 'https://www.explodingkittens.com/pages/rules-kittens'
  },
  {
    id: 'game-18',
    name: 'Saboteur',
    description: `Saboteur è un gioco di carte per 3-10 giocatori della durata di circa 30 minuti, in cui i partecipanti interpretano nani minatori con ruoli segreti, cercando di costruire o sabotare tunnel per raggiungere l'oro.`,
    image: 'games/saboteur.jpg',
    players: { min: 3, max: 10 },
    time: { min: 20, max: 40 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'ruoli segreti', 'carte', 'bluff', 'gruppi numerosi'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: 1.38,
    pdfLink: 'https://www.goblins.net/files/download/saboter_ITArules.pdf'
  },
  {
    id: 'game-19',
    name: 'Bang! La Pallottola',
    description: `Bang! La Pallottola è un gioco di carte per 4-7 giocatori della durata di circa 30-40 minuti, ambientato nel Far West, in cui i partecipanti assumono ruoli segreti e si eliminano a colpi di carte tra bluff, deduzione e alleanze.`,
    image: 'games/bang.jpg',
    imageClass: 'img-soft-cover',
    players: { min: 4, max: 7 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'ruoli segreti', 'carte', 'bluff', 'gruppo'],
    macroCategory: 'party game',
    difficulty: 2,
    weightBGG: 1.65,
    pdfLink: 'https://www.dvgiochi.com/giochi/bang/Bang_rules_IT.pdf'
  },
  {
    id: 'game-20',
    name: 'Monopoly',
    description: `Monopoly è un gioco da tavolo per 2-6 giocatori della durata di circa 60-180 minuti, in cui i partecipanti comprano, scambiano e sviluppano proprietà immobiliari cercando di mandare in bancarotta gli avversari.`,
    image: 'games/monopoly.jpg',
    players: { min: 2, max: 6 },
    time: { min: 60, max: 180 },
    playtimeCategory: '> 60 min',
    tags: ['familiare', 'economico', 'competitivo', 'classico'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: 1.19,
    pdfLink: 'https://instructions.hasbro.com/api/download/C1009_it-it_monopoly-classic-game.pdf'
  },
  {
    id: 'game-21',
    name: 'Labirinto',
    description: `Labirinto è un gioco da tavolo per 2-4 giocatori della durata di circa 20-30 minuti, in cui i partecipanti modificano un labirinto scorrevole per raggiungere tesori nascosti prima degli avversari.`,
    image: 'games/labirinto.jpg',
    imageClass: 'img-horizontal',
    players: { min: 2, max: 4 },
    time: { min: 20, max: 30 },
    playtimeCategory: '< 30 min',
    tags: ['familiare', 'movimento', 'leggero', 'competitivo'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: 1.35
  },
  {
    id: 'game-22',
    name: 'Hive',
    description: `Hive è un gioco scacchistico per 2 giocatori della durata di circa 20-30 minuti, in cui i partecipanti muovono insetti con abilità uniche cercando di circondare l'ape regina avversaria.`,
    image: 'games/hive.jpg',
    players: { min: 2, max: 2 },
    time: { min: 20, max: 30 },
    playtimeCategory: '< 30 min',
    tags: ['astratto', 'strategico', 'duello', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 2.32
  },
  {
    id: 'game-23',
    name: 'Slapzi',
    description: `Slapzi è un gioco di carte rapido per 2-8 giocatori della durata di circa 10-15 minuti, in cui i partecipanti associano velocemente carte immagine e carte parola per essere i primi a liberarsi della mano.`,
    image: 'games/slapzi.png',
    imageClass: 'img-horizontal',
    players: { min: 2, max: 8 },
    time: { min: 10, max: 20 },
    playtimeCategory: '< 30 min',
    tags: ['party', 'velocità', 'familiare', 'leggero'],
    macroCategory: 'party game',
    difficulty: 0,
    weightBGG: '0 (non da BGG)'
  },
  {
    id: 'game-24',
    name: 'Unstable Unicorns',
    description: `Unstable Unicorns è un gioco di carte per 2-8 giocatori della durata di circa 30-45 minuti, in cui i partecipanti costruiscono eserciti di unicorni sabotando gli avversari con carte azione e colpi di scena.`,
    image: 'games/unstable unicorns.jpg',
    imageClass: 'img-horizontal',
    players: { min: 2, max: 8 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'carte', 'caotico', 'competitivo'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: 1.49
  },
  {
    id: 'game-25',
    name: 'Munchkin',
    description: `Munchkin è un gioco di carte per 3-6 giocatori della durata di circa 60-90 minuti, in cui i partecipanti esplorano dungeon, combattono mostri e tradiscono gli alleati per raggiungere per primi il livello 10.`,
    image: 'games/munchkin.jpg',
    imageClass: 'img-soft-cover',
    players: { min: 3, max: 6 },
    time: { min: 60, max: 120 },
    playtimeCategory: '> 60 min',
    tags: ['party', 'carte', 'umoristico', 'competitivo'],
    macroCategory: 'party game',
    difficulty: 2,
    weightBGG: 1.61
  },
  {
    id: 'game-26',
    name: 'Santorini',
    description: `Santorini è un gioco astratto per 2-4 giocatori della durata di circa 20-30 minuti, in cui i partecipanti costruiscono edifici e muovono i propri personaggi usando poteri divini per ottenere vantaggi strategici.`,
    image: 'games/santorini.jpg',
    players: { min: 2, max: 4 },
    time: { min: 20, max: 30 },
    playtimeCategory: '< 30 min',
    tags: ['astratto', 'strategico', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: 2.35
  },
  {
    id: 'game-27',
    name: 'Pandemic Legacy Season 1',
    description: `Pandemic Legacy Season 1 è un gioco cooperativo per 2-4 giocatori della durata di circa 60 minuti a partita, in cui i partecipanti affrontano una campagna narrativa evolutiva cercando di salvare l'umanità in un mondo post-apocalittico.`,
    image: 'games/pandemic legacy season 1.jpg',
    imageClass: 'img-horizontal',
    players: { min: 2, max: 4 },
    time: { min: 60, max: 120 },
    playtimeCategory: '> 60 min',
    tags: ['cooperativo', 'campagna', 'narrativo', 'pesante'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: 3.26
  },
  {
    id: 'game-28',
    name: 'Paladin',
    description: `Paladin è un gioco da tavolo strategico per 1-4 giocatori della durata di circa 60-120 minuti, in cui i partecipanti gestiscono risorse, lavoratori e azioni per sviluppare il proprio regno medievale.`,
    image: 'games/paladin.jpg',
    imageClass: 'img-horizontal',
    players: { min: 1, max: 4 },
    time: { min: 60, max: 120 },
    playtimeCategory: '> 60 min',
    tags: ['strategico', 'gestionale', 'pesante', 'solitario'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: 3.01
  },
  {
    id: 'game-29',
    name: 'Taboo',
    description: `Taboo è un party game per 4-8 giocatori della durata di circa 20-30 minuti, in cui i partecipanti devono far indovinare parole evitando termini proibiti, creando situazioni caotiche e divertenti.`,
    image: 'games/Taboo.jpg',
    players: { min: 4, max: 8 },
    time: { min: 20, max: 30 },
    playtimeCategory: '< 30 min',
    tags: ['party', 'parole', 'gruppi numerosi', 'familiare'],
    macroCategory: 'party game',
    difficulty: 0,
    weightBGG: 1.1
  },
  {
    id: 'game-30',
    name: 'Sky Team',
    description: `Sky Team è un gioco cooperativo per 2 giocatori in cui i partecipanti collaborano per far atterrare un aereo in sicurezza gestendo velocità, asse centrale e comunicazione.`,
    image: 'games/Sky Team.jpg',
    players: { min: 2, max: 2 },
    time: { min: 15, max: 30 },
    playtimeCategory: 'Meno di 30 min',
    tags: ['cooperativo', 'strategico', 'a due', 'tattico'],
    macroCategory: 'strategici',
    difficulty: 3,
    weightBGG: '2.4 (non da BGG)'
  },
  {
    id: 'game-31',
    name: 'Citadels',
    description: `Citadels è un gioco di carte e ruoli in cui i giocatori costruiscono città e utilizzano abilità speciali dei personaggi per accumulare punti vittoria.`,
    image: 'games/Citadels.jpg',
    players: { min: 2, max: 7 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['carte', 'strategico', 'ruoli', 'competitivo'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: '2.1 (non da BGG)'
  },
  {
    id: 'game-32',
    name: 'Patchwork',
    description: `Patchwork è un gioco strategico per 2 giocatori in cui si costruisce una coperta patchwork ottimizzando risorse, tempo e posizionamento delle tessere.`,
    image: 'games/Patchwork.jpg',
    players: { min: 2, max: 2 },
    time: { min: 15, max: 30 },
    playtimeCategory: 'Meno di 30 min',
    tags: ['astratto', 'strategico', 'tattico', 'a due'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: '1.8 (non da BGG)'
  },
  {
    id: 'game-33',
    name: 'Piccioni Esplosivi',
    description: `Piccioni Esplosivi è un party game veloce e caotico in cui i giocatori si lanciano carte e sabotaggi per eliminarsi a vicenda.`,
    image: 'games/Piccioni Esplosivi.jpg',
    players: { min: 2, max: 6 },
    time: { min: 10, max: 20 },
    playtimeCategory: 'Meno di 30 min',
    tags: ['party', 'veloce', 'divertente', 'carte'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: '1 (non da BGG)'
  },
  {
    id: 'game-34',
    name: 'The Crew: Missioni nello Spazio',
    description: `The Crew è un gioco cooperativo di prese ambientato nello spazio, in cui i giocatori devono completare missioni comunicando in modo limitato.`,
    image: 'games/The Crew Spazio.jpg',
    players: { min: 2, max: 5 },
    time: { min: 20, max: 40 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['cooperativo', 'carte', 'strategico', 'missioni'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: '2.2 (non da BGG)'
  },
  {
    id: 'game-35',
    name: 'Dixit',
    description: `Dixit è un party game creativo basato su immagini e narrazione, in cui i giocatori devono indovinare le carte tramite indizi astratti.`,
    image: 'games/Dixit.jpg',
    players: { min: 3, max: 8 },
    time: { min: 20, max: 40 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['creativo', 'party', 'narrazione', 'immaginazione'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: '1.3 (non da BGG)'
  },
  {
    id: 'game-36',
    name: 'Catan per 2 giocatori - gioco di carte',
    description: `Versione a due giocatori di Catan, dove i partecipanti competono per raccogliere risorse e costruire strade e insediamenti in un formato rapido e strategico.`,
    image: 'games/Catan 2 giocatori.jpg',
    players: { min: 2, max: 2 },
    time: { min: 20, max: 40 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['carte', 'strategico', 'a due', 'risorse'],
    macroCategory: 'strategici',
    difficulty: 2,
    weightBGG: '2 (non da BGG)'
  },
  {
    id: 'game-37',
    name: 'Scacchi',
    description: `Scacchi è il classico gioco da tavolo strategico per due giocatori, basato su mosse tattiche e pianificazione a lungo termine.`,
    image: 'games/Scacchi.jpg',
    players: { min: 2, max: 2 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['astratto', 'strategico', 'tattico', 'a due'],
    macroCategory: 'strategici',
    difficulty: 4,
    weightBGG: '3.5 (non da BGG)'
  },
  {
    id: 'game-38',
    name: 'Gioco di dadi di Jack Sparrow',
    description: `Gioco di dadi ispirato a Pirati dei Caraibi, in cui i giocatori lanciano dadi per ottenere tesori e completare missioni in un party game veloce e divertente.`,
    image: 'games/Dadi Jack Sparrow.jpg',
    players: { min: 2, max: 6 },
    time: { min: 15, max: 30 },
    playtimeCategory: 'Meno di 30 min',
    tags: ['party', 'dadi', 'veloce', 'divertente'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: '1 (non da BGG)'
  },
  {
    id: 'game-39',
    name: "Gioco dell'Impostore (gioco di parole)",
    description: `Gioco di parole e deduzione sociale in cui i giocatori devono scoprire l'impostore tra loro, divertente e adatto a gruppi grandi.`,
    image: "games/Gioco dell'Impostore.jpg",
    players: { min: 4, max: 10 },
    time: { min: 20, max: 40 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'parole', 'sociale', 'divertente'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: '1.2 (non da BGG)'
  },
  {
    id: 'game-40',
    name: 'Lupus in Tabula',
    description: `Lupus in Tabula è un gioco di deduzione sociale e bluff in cui i giocatori devono scoprire chi sono i lupi mannari nascosti tra di loro.`,
    image: 'games/Lupus in Tabula.jpg',
    players: { min: 6, max: 18 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'bluff', 'sociale', 'deduzione'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: '1.5 (non da BGG)'
  },
  {
    id: 'game-41',
    name: 'Avalon',
    description: `Avalon è un gioco di deduzione sociale ambientato nel ciclo arturiano, in cui i giocatori assumono ruoli segreti e cercano di completare missioni o sabotarle.`,
    image: 'games/Avalon.jpg',
    players: { min: 5, max: 10 },
    time: { min: 30, max: 60 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'bluff', 'sociale', 'deduzione'],
    macroCategory: 'party game',
    difficulty: 2,
    weightBGG: '2 (non da BGG)'
  },
  {
    id: 'game-42',
    name: 'When I Dream',
    description: `When I Dream è un party game creativo in cui un giocatore deve indovinare parole mentre gli altri lo aiutano o lo confondono attraverso indizi, bluff e immaginazione.`,
    image: 'games/When I Dream.jpg',
    players: { min: 4, max: 10 },
    time: { min: 30, max: 45 },
    playtimeCategory: 'Tra 30 e 60 min',
    tags: ['party', 'creativo', 'immaginazione', 'deduzione'],
    macroCategory: 'party game',
    difficulty: 1,
    weightBGG: '1.7 (non da BGG)',
    pdfLink: 'https://cdn.1j1ju.com/medias/e5/06/28-when-i-dream-rule.pdf'
  },
  {
  id: 'game-43',
  name: '13 Foglie',
  description: `13 Foglie è un gioco di carte rapido e strategico in cui i giocatori devono giocare una o più carte dello stesso valore per estendere la sequenza sul tavolo. L'obiettivo è liberarsi delle proprie carte prima degli altri, cercando allo stesso tempo di bloccare le mosse degli avversari e costruire una sequenza numerica armoniosa.`,
  image: 'games/13 Foglie.jpg',
  players: { min: 3, max: 6 },
  time: { min: 15, max: 20 },
  playtimeCategory: 'Meno di 30 min',
  tags: ['carte', 'sequenze', 'hand management', 'set collection'],
  macroCategory: 'party game',
  difficulty: 1,
  weightBGG: '1.5 (stima)',
  pdfLink: 'https://www.craniocreations.it/storage/media/product_downloads/177/2009/13Foglie_Regolamento-ITA_low.pdf'
},
  {
  id: 'game-44',
  name: 'Elden Letter',
  description: `Elden Letter è un party game di deduzione rapido in cui i giocatori cercano di ottenere la grazie di Dafne la strega prima degli altri. Ogni turno si pesca una carta e se ne gioca una, attivando l'abilità del personaggio per ottenere informazioni, proteggersi o eliminare gli avversari dal round. Il gioco combina bluff, intuizione e rischio in partite veloci e piene di tensione.`,
  image: 'games/elden letter.png',
  players: { min: 2, max: 6 },
  time: { min: 15, max: 20 },
  playtimeCategory: 'Meno di 30 min',
  tags: ['carte', 'deduzione', 'bluff', 'eliminazione giocatori', 'hand management'],
  macroCategory: 'party game',
  difficulty: 1,
  weightBGG: '1.18',
  pdfLink: '/games/Elden_letter_regolamento.pdf'
}
];
